print("***** WELCOME *****")
word = input("Please enter a word: ")

word = list(word.lower())
counter_a = word.count("a")
counter_e = word.count("e")
counter_i = word.count("i")
counter_o = word.count("o")
counter_u = word.count("u")
print("The vowel a appears: ",counter_a, "times")
print("The vowel e appears: ",counter_e, "times")
print("The vowel i appears: ",counter_i, "times")
print("The vowel o appears: ",counter_o, "times")
print("The vowel u appears: ",counter_u, "times")